name: Trigger Main Repo Sync

on:
  push:
    branches:
      - main

jobs:
  trigger-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Update submodules to the latest commit from their remote branches
        run: git submodule update --remote --merge

      - name: Trigger main repository update
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#*/}"

          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Innocenttt3/Medical-IT-systems-team-project/dispatches \
            -d "{
              \"event_type\": \"submodule-main-updated\",
              \"client_payload\": {
                \"submodule\": \"$REPO_NAME\",
                \"commit\": \"$GITHUB_SHA\"
              }
            }"
